# Generated by Django 5.1.4 on 2024-12-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='promocode',
            new_name='promo',
        ),
    ]
