# Generated by Django 4.2.16 on 2025-03-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.product'),
        ),
    ]
